version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: somes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dataservice,eu-dataservice # AT (default), eu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: somes-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: somes-meilisearch
    command: meilisearch --experimental-contains-filter
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meilidata:/data.ms

volumes:
  pgdata:
  redisdata:
  meilidata:
