use axum::Json;
use somes_common_lib::LegisPeriod;
use utoipa::ToSchema;
mod absences_per_age;
mod absences_per_delegate;
mod absences_per_gender;
mod absences_per_legis;
mod absences_per_party;
mod absolute_majority_initiatives;
mod activity_per_age;
mod activity_per_delegate;
mod activity_per_gender;
mod activity_per_legis;
mod activity_per_party;
mod age_of_delegates;
mod age_per_gender;
mod age_per_legis;
mod age_per_party;
mod call_to_orders;
mod call_to_orders_by_delegate;
mod call_to_orders_per_age;
mod call_to_orders_per_gender;
mod call_to_orders_per_legis;
mod call_to_orders_per_party;
mod complexity_at_age;
mod complexity_per_gender;
mod complexity_per_legis;
mod complexity_per_party;
mod complexity_per_person;
mod division_accuracy_score_per_age;
mod division_accuracy_score_per_delegate;
mod division_accuracy_score_per_gender;
mod division_accuracy_score_per_legis;
mod division_accuracy_score_per_party;
mod error;
pub mod filtering;
mod is_left_per_age;
mod is_left_per_delegate;
mod is_left_per_gender;
mod is_left_per_legis;
mod is_left_per_party;
mod is_liberal_per_age;
mod is_liberal_per_delegate;
mod is_liberal_per_gender;
mod is_liberal_per_legis;
mod is_liberal_per_party;
mod speechtime_per_age;
mod speechtime_per_delegate;
mod speechtime_per_gender;
mod speechtime_per_legis;
mod speechtime_per_party;
mod total_speeches_per_age;
mod total_speeches_per_delegate;
mod total_speeches_per_gender;
mod total_speeches_per_legis;
mod total_speeches_per_party;
mod votes_together;

pub use absences_per_age::*;
pub use absences_per_delegate::*;
pub use absences_per_gender::*;
pub use absences_per_legis::*;
pub use absences_per_party::*;
pub use absolute_majority_initiatives::*;
pub use activity_per_age::*;
pub use activity_per_delegate::*;
pub use activity_per_gender::*;
pub use activity_per_legis::*;
pub use activity_per_party::*;
pub use age_of_delegates::*;
pub use age_per_gender::*;
pub use age_per_legis::*;
pub use age_per_party::*;
pub use call_to_orders::*;
pub use call_to_orders_by_delegate::*;
pub use call_to_orders_per_age::*;
pub use call_to_orders_per_gender::*;
pub use call_to_orders_per_legis::*;
pub use call_to_orders_per_party::*;
pub use complexity_at_age::*;
pub use complexity_per_gender::*;
pub use complexity_per_legis::*;
pub use complexity_per_party::*;
pub use complexity_per_person::*;
pub use division_accuracy_score_per_age::*;
pub use division_accuracy_score_per_delegate::*;
pub use division_accuracy_score_per_gender::*;
pub use division_accuracy_score_per_legis::*;
pub use division_accuracy_score_per_party::*;
pub use is_left_per_age::*;
pub use is_left_per_delegate::*;
pub use is_left_per_gender::*;
pub use is_left_per_legis::*;
pub use is_left_per_party::*;
pub use is_liberal_per_age::*;
pub use is_liberal_per_delegate::*;
pub use is_liberal_per_gender::*;
pub use is_liberal_per_legis::*;
pub use is_liberal_per_party::*;
pub use speechtime_per_age::*;
pub use speechtime_per_delegate::*;
pub use speechtime_per_gender::*;
pub use speechtime_per_legis::*;
pub use speechtime_per_party::*;
pub use total_speeches_per_age::*;
pub use total_speeches_per_delegate::*;
pub use total_speeches_per_gender::*;
pub use total_speeches_per_party::*;
pub use votes_together::*;

pub use self::total_speeches_per_legis::*;
