export const topicColors: Map<string, string> = new Map([
	['Sport', '#006400'], // Dunkelgrün
	['Budget und Finanzen', '#FFD700'], // Gold
	['Information und Medien', '#4B0082'], // Indigo
	['Arbeit', '#4682B4'], // Stahlblau
	['Europäische Union', '#4169E1'], // Königsblau
	['Familie und Generationen', '#B76E79'], // Roségold
	['Gesundheit und Ernährung', '#191970'], // Mitternachtsblau
	['Klima, Umwelt und Energie', '#008000'], // Smaragdgrün
	['Frauen und Gleichbehandlung', '#DCB0D0'], // Malvenfarben
	['Verkehr und Infrastruktur', '#FF8C00'], // Dunkelorange
	['Inneres und Recht', '#800000'], // Granatrot
	['Innovation, Technologie und Forschung', '#008080'], // Teal
	['Bildung', '#0F52BA'], // Saphirblau
	['Wirtschaft', '#8B008B'], // Dunkles Magenta
	['Landesverteidigung', '#556B2F'], // Olivgrün
	['Parlament und Demokratie', '#FF6F61'], // Korallenrot
	['Außenpolitik', '#800020'], // Burgunderrot
	['Land- und Forstwirtschaft', '#A0522D'], // Siena
	['Soziales', '#FFE5B4'], // Pfirsich
	['Kultur', '#8A2BE2'] // Violett
]);

export const TOPIC_MAP: Record<string, string> = {
	Arbeitsrecht: 'Arbeit',
	'Beschäftigung und Arbeitsbedingungen': 'Arbeit',
	Arbeitslosenversicherung: 'Arbeit',
	Gewerbeaufsicht: 'Arbeit',
	Unternehmensarten: 'Arbeit',
	'Verwaltung und Entlohnung des Personals': 'Arbeit',
	'internationales Abkommen': 'Außenpolitik',
	'Internationale Beziehungen': 'Außenpolitik',
	'diplomatische Beziehungen': 'Außenpolitik',
	'Vereinte Nationen': 'Außenpolitik',
	Völkerrecht: 'Außenpolitik',
	'völkerrechtliche Verantwortlichkeit': 'Außenpolitik',
	'Politik der Zusammenarbeit': 'Außenpolitik',
	Europarat: 'Außenpolitik',
	'Interparlamentarische Union': 'Außenpolitik',
	Hochschulausbildung: 'Bildung',
	'Organisation des Unterrichtswesens': 'Bildung',
	Bildung: 'Bildung',
	Sekundarstufe: 'Bildung',
	Primarstufe: 'Bildung',
	'vorschulische Erziehung': 'Bildung',
	Erwachsenenbildung: 'Bildung',
	Ausbildungsbeihilfe: 'Bildung',
	'Öffentliche Finanzen und Haushaltspolitik': 'Budget und Finanzen',
	Finanzwesen: 'Budget und Finanzen',
	Steuerwesen: 'Budget und Finanzen',
	Haushaltsplan: 'Budget und Finanzen',
	Haushaltskontrolle: 'Budget und Finanzen',
	Finanzausgleich: 'Budget und Finanzen',
	Nachtragshaushaltsplan: 'Budget und Finanzen',
	Einkommen: 'Budget und Finanzen',
	Buchprüfung: 'Budget und Finanzen',
	Währungsbeziehungen: 'Budget und Finanzen',
	'Europäische Union': 'Europäische Union',
	Familie: 'Familie und Generationen',
	Familienleistungsausgleich: 'Familie und Generationen',
	'junger Mensch': 'Familie und Generationen',
	Frau: 'Frauen und Gleichbehandlung',
	Gleichbehandlung: 'Frauen und Gleichbehandlung',
	Gesundheit: 'Gesundheit und Ernährung',
	Krankenpflege: 'Gesundheit und Ernährung',
	'Betreuung von Pflegebedürftigen': 'Gesundheit und Ernährung',
	Apotheke: 'Gesundheit und Ernährung',
	Altersversorgungssystem: 'Gesundheit und Ernährung',
	'soziale Sicherheit': 'Gesundheit und Ernährung',
	Tabak: 'Gesundheit und Ernährung',
	Wein: 'Gesundheit und Ernährung',
	Weinbau: 'Gesundheit und Ernährung',
	Branntwein: 'Gesundheit und Ernährung',
	Salz: 'Gesundheit und Ernährung',
	'Agrarerzeugnisse und Lebensmittel': 'Gesundheit und Ernährung',
	Fernsehen: 'Information und Medien',
	Hörfunk: 'Information und Medien',
	Presse: 'Information und Medien',
	'Post- und Fernmeldewesen': 'Information und Medien',
	Internet: 'Information und Medien',
	Telekommunikation: 'Information und Medien',
	'Information und Informationsverarbeitung': 'Information und Medien',
	Opferhilfe: 'Inneres und Recht',
	Strafrecht: 'Inneres und Recht',
	Verfassung: 'Inneres und Recht',
	Verwaltungsrecht: 'Inneres und Recht',
	'öffentliche Verwaltung': 'Inneres und Recht',
	'öffentlicher Dienst': 'Inneres und Recht',
	Exekutive: 'Inneres und Recht',
	Misstrauensantrag: 'Inneres und Recht',
	Staatsangehöriger: 'Inneres und Recht',
	'Bürgerliches Recht': 'Inneres und Recht',
	Menschenrechte: 'Inneres und Recht',
	Gerichtswesen: 'Inneres und Recht',
	Notar: 'Inneres und Recht',
	Rechtsanwalt: 'Inneres und Recht',
	'öffentliches Eigentum': 'Inneres und Recht',
	Verfassungsgerichtsbarkeit: 'Inneres und Recht',
	Verwaltungsgerichtsbarkeit: 'Inneres und Recht',
	Verwaltungsorganisation: 'Inneres und Recht',
	Verwaltungsreform: 'Inneres und Recht',
	Verwaltungskontrolle: 'Inneres und Recht',
	'Vereinfachung der Rechtsvorschriften': 'Inneres und Recht',
	Religion: 'Inneres und Recht',
	Versammlungsfreiheit: 'Inneres und Recht',
	Flüchtling: 'Inneres und Recht',
	Staatschef: 'Inneres und Recht',
	Ausweis: 'Inneres und Recht',
	Staatswald: 'Inneres und Recht',
	Inkompatibilität: 'Inneres und Recht',
	'Veröffentlichung des Gesetzes': 'Inneres und Recht',
	Neutralität: 'Inneres und Recht',
	'gesetzlicher Feiertag': 'Inneres und Recht',
	Staatssymbol: 'Inneres und Recht',
	Personenstand: 'Inneres und Recht',
	Zivilschutz: 'Inneres und Recht',
	'öffentliche Sicherheit': 'Inneres und Recht',
	Informatik: 'Innovation, Technologie und Forschung',
	'Forschung und geistiges Eigentum': 'Innovation, Technologie und Forschung',
	Wissenschaften: 'Innovation, Technologie und Forschung',
	Statistik: 'Innovation, Technologie und Forschung',
	Geodäsie: 'Innovation, Technologie und Forschung',
	'Maße und Gewichte': 'Innovation, Technologie und Forschung',
	Umwelt: 'Klima, Umwelt und Energie',
	Abfall: 'Klima, Umwelt und Energie',
	Abfallwirtschaft: 'Klima, Umwelt und Energie',
	Energie: 'Klima, Umwelt und Energie',
	Elektrizitätsindustrie: 'Klima, Umwelt und Energie',
	'Elektrizitäts- und Kernkraftindustrie': 'Klima, Umwelt und Energie',
	Wasser: 'Klima, Umwelt und Energie',
	Wasserbewirtschaftung: 'Klima, Umwelt und Energie',
	Wasserbau: 'Klima, Umwelt und Energie',
	Kulturpolitik: 'Kultur',
	Kunst: 'Kultur',
	Museum: 'Kultur',
	Bibliothek: 'Kultur',
	Filmindustrie: 'Kultur',
	'Darstellende Künste': 'Kultur',
	Vereinsleben: 'Kultur',
	'ehrende Auszeichnung': 'Kultur',
	Preis: 'Kultur',
	Verteidigung: 'Landesverteidigung',
	Zivildienst: 'Landesverteidigung',
	'Land- und Forstwirtschaft, Fischerei': 'Land- und Forstwirtschaft',
	Fischerei: 'Land- und Forstwirtschaft',
	Jagd: 'Land- und Forstwirtschaft',
	Bodenreform: 'Land- und Forstwirtschaft',
	'Geschäftsordnung des Parlaments': 'Parlament und Demokratie',
	Ausschussbericht: 'Parlament und Demokratie',
	Parlamentarier: 'Parlament und Demokratie',
	Parlamentsdebatte: 'Parlament und Demokratie',
	'parlamentarischer Ausschuss': 'Parlament und Demokratie',
	'direkt gewählte Kammer': 'Parlament und Demokratie',
	'Zweite Kammer': 'Parlament und Demokratie',
	Zweikammersystem: 'Parlament und Demokratie',
	Gesetzgebungsverfahren: 'Parlament und Demokratie',
	'partizipative Demokratie': 'Parlament und Demokratie',
	'namentliche Abstimmung': 'Parlament und Demokratie',
	Regierungserklärung: 'Parlament und Demokratie',
	'öffentliche Anhörung': 'Parlament und Demokratie',
	'parlamentarische Immunität': 'Parlament und Demokratie',
	'Zusammensetzung des Parlaments': 'Parlament und Demokratie',
	Parlamentssitzung: 'Parlament und Demokratie',
	Föderalismus: 'Parlament und Demokratie',
	Gliedstaat: 'Parlament und Demokratie',
	'Politische Partei': 'Parlament und Demokratie',
	'Mensch mit Behinderung': 'Soziales',
	Sozialpolitik: 'Soziales',
	Sport: 'Sport',
	Schienentransport: 'Verkehr und Infrastruktur',
	Wohnungspolitik: 'Verkehr und Infrastruktur',
	Straßenverkehr: 'Verkehr und Infrastruktur',
	Luftverkehr: 'Verkehr und Infrastruktur',
	'See- und Binnenschiffsverkehr': 'Verkehr und Infrastruktur',
	'Straßen- und Brückenbau': 'Verkehr und Infrastruktur',
	'Bauindustrie und öffentliches Bauwesen': 'Verkehr und Infrastruktur',
	Baupolitik: 'Verkehr und Infrastruktur',
	Verkehr: 'Verkehr und Infrastruktur',
	Raumordnung: 'Verkehr und Infrastruktur',
	Grenze: 'Verkehr und Infrastruktur',
	Tourismus: 'Verkehr und Infrastruktur',
	Handel: 'Wirtschaft',
	Industrie: 'Wirtschaft',
	Wirtschaft: 'Wirtschaft',
	Zolltarifpolitik: 'Wirtschaft',
	'Unternehmen und Wettbewerb': 'Wirtschaft',
	Versicherungswesen: 'Wirtschaft',
	Glücksspiel: 'Wirtschaft',
	Berufsverband: 'Wirtschaft',
	'Öffentlicher Sektor': 'Sonstige',
	Personalvertretung: 'Sonstige',
	Archiv: 'Sonstige',
	'Trentino-Südtirol': 'Sonstige',
	'ethnische Gruppe': 'Sonstige',
	Volkszählung: 'Sonstige'
};

export function translateTopicToParent(complexTopic: string): string {
	return TOPIC_MAP[complexTopic] ?? 'Sonstige';
}
